feat(responsemanager): use TaskQueue to handle execution management
ipfs/go-graphsync pull request #244
Opened 2021-10-08 10:27 UTC by rvagg

Fixes: https://github.com/ipfs/go-graphsync/issues/232

Just a very initial batch of work to make _something_ happen and I'm a little surprised that I managed to get this working and tests passing so I think I'm on the right track at least. Quite a bit more work needed.

The main concern so far was the need for adding a `TaskQueue#Remove()`, I hope this is an expected difference between the responsemanager and requestmanager.

2021-10-18 22:13 UTC, hannahhoward commented
looks good so far. :)

2021-10-23 00:41 UTC, hannahhoward reviewed
@rvagg this is looking good. Don't get discouraged about testing for the QueryExecutor -- let's pair together when you have a chance to get it done.

2021-10-23 00:41 UTC, hannahhoward commented on responsemanager/client.go
> +	ThawSpeed = time.Millisecond * 100
do we need this here any more?

2021-10-23 00:41 UTC, hannahhoward commented on responsemanager/responsemanager_test.go
> +	queryExecutor := td.newQueryExecutor(rm)
This is the right approach for this test -- it's already basically quite an integration test -- it doesn't run the whole stack, but it's mean to test the response manager as a whole unit together. I'd rather continue to to that then mock out a whole bunch of stuff. It feels much more real and useful to me

2021-11-16 03:27 UTC, hannahhoward requested changes
Immediate blockers:
1. Remove all refs to workSignal  -- it should be unneccesary for either QueryExecutor or ResponseManager to have that channel.
2. Delete RunTraversal if we are no longer using it
3. I'd like to understand why we have new test flakiness. We didn't really have that when we switched the RequestManager over

2021-11-16 03:27 UTC, hannahhoward commented on impl/graphsync.go
> +	responseWorkSignal := make(chan struct{}, 1)
Work signal is all already handled inside the TaskQueue -- generally, we shouldn't see it any were. You can remove all references to work signal from both ResponseManager and QueryExecutor.

2021-11-16 03:27 UTC, hannahhoward commented on responsemanager/queryexecutor/queryexecutor.go
> +package queryexecutor
+1 for this test -- it's looking good and we haven't had this up till now so I'm excited about that

2021-11-16 03:27 UTC, hannahhoward commented on responsemanager/queryexecutor/queryexecutor.go
> +		if err != nil {
sidebar, not for this PR -- I think we should make this a switch statement on err -- it would probably make for less complicated to understand code.

2021-11-16 04:07 UTC, rvagg commented
I haven't managed to replicate the `-race` failure for `TestValidationAndExtensions/hooks_can_alter_the_loader` as noted in #267, but after some repeats I managed to get a failure for `TestValidationAndExtensions/test_update_hook_processing/can_send_extension_data/when_paused`. Recording here because it seems that this is rare:

```
--- FAIL: TestValidationAndExtensions (10.77s)
    --- FAIL: TestValidationAndExtensions/test_update_hook_processing (10.22s)
        --- FAIL: TestValidationAndExtensions/test_update_hook_processing/can_send_extension_data (10.02s)
            --- FAIL: TestValidationAndExtensions/test_update_hook_processing/can_send_extension_data/when_paused (10.00s)
                channelassertions.go:41:
                        Error Trace:    channelassertions.go:41
                                                                channelassertions.go:13
                                                                responsemanager_test.go:1168
                                                                responsemanager_test.go:639
                        Error:          Not equal:
                                        expected: 0
                                        actual  : 1
                        Test:           TestValidationAndExtensions/test_update_hook_processing/can_send_extension_data/when_paused
                        Messages:       should send extension response
```

Interestingly, and maybe concerningly, it also spits this out:

```
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```

(this was with `-count 99`, perhaps goroutines stack up between simultaneous runs of `go test` and we're not cleaning up properly somewhere?)

2021-11-16 05:19 UTC, rvagg commented
Capturing the race failure from #267 in https://github.com/ipfs/go-graphsync/runs/4218540124 `TestValidationAndExtensions/hooks_can_alter_the_loader` looks like probably the same failure, but also I haven't been able to make this happen again locally:

```
  === RUN   TestValidationAndExtensions/hooks_can_alter_the_loader
  2021-11-15T23:41:08.747Z	ERROR	gs-queryexecutor	failed to load link=bafyreif5yjx4fabs35j7sqsvpcgwyvju2ys3a7gmlr7rod4bc54fwnf2w4, nBlocksRead=0, err=unable to load block
  2021-11-15T23:41:08.747Z	ERROR	gs-queryexecutor	traversal completion check failed, nBlocksRead=0, err=skip
      channelassertions.go:41: 
          	Error Trace:	channelassertions.go:41
          	            				channelassertions.go:13
          	            				responsemanager_test.go:1155
          	            				responsemanager_test.go:1146
          	            				responsemanager_test.go:306
          	Error:      	Not equal: 
          	            	expected: 0
          	            	actual  : 1
          	Test:       	TestValidationAndExtensions/hooks_can_alter_the_loader
          	Messages:   	should complete request
```

2021-11-16 05:23 UTC, rvagg commented
Maybe not quite the same failure, that one is while waiting for something on `td.completedRequestChan` while the `test_update_hook_processing` one is while waiting for something on `td.sentExtensions`. Both are touched in `QueryExecutor#sendResponse` so very likely the same cause. And I'm still guessing it's got to do with externalising the parallelisation to taskqueue rather than the `RunTraversal` refactor.

2021-11-16 15:11 UTC, hannahhoward approved these changes

2021-11-16 15:41 UTC, hannahhoward commented
Hey @rvagg, I think it's time to merge. We've got a ton of working good code here and I'm feeling not super worried about the test flakiness.

However, I wrote a quick spike to make a task executor that runs immediately in test https://github.com/ipfs/go-graphsync/pull/270 as well, so hopefully this will help with the flakiness.

2021-11-17 00:04 UTC, merged

2021-11-17 01:39 UTC, rvagg commented
Noting easy path to replicating one of the flakys:

```
go test -count 99 -run TestValidationAndExtensions/test_update_hook_processing/can_send_extension_data/when_paused
```